Testing Nested try block with multiple catch block inside the try block of the outer try block PASSED!
